# Site settings
title: Phil Kaufman - Test Automation Engineer
email: philipkaufman@hotmail.co.uk
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/philipkaufman/" # the subpath of your site, e.g. /blog/
url: "https://philkky.github.io" # the base hostname & protocol for your site
twitter_username: philkky
github_username:  philkky

# Build settings
markdown: kramdown
