# Site settings
title: Phil Kaufman - Test Automation Engineer
email: philipkaufman@hotmai.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "https://philkky.github.io/philipkaufman/" # the subpath of your site, e.g. /blog/
url: "https://philkky.github.io" # the base hostname & protocol for your site
twitter_username: philkky
github_username:  philkky

# Build settings
markdown: kramdown
